POST http://localhost:5059/events
Content-Type: application/json

{
	"name": "Test event 2",
	"description": "A test event 2",
	"location": "A test Location 2",
	"dateTime": "2025-01-10T15:30:00.000Z"
}